services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # host.docker.internal resuelve al localhost de Windows/Mac
      - OLLAMA_URL=http://host.docker.internal:11434
      - MODEL_NAME=llama3.2
      - JAVA_HOME=/usr/lib/jvm/default-java

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
