services:
  backend:
    build: ./backend
    network_mode: "host"
    volumes:
      - ./backend:/app
      - ./ontologia_variables_categoricas_corregida.owx:/app/ontology.owx
    environment:
      - OLLAMA_URL=http://localhost:11434
      - MODEL_NAME=llama3.2
      - JAVA_HOME=/usr/lib/jvm/default-java

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
